version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
      - "80:80"
    links:
      - fpm
    volumes:
      - ./public:/var/www/hrms/public:cached
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf

  fpm:
    build: ./
    links:
      - db
    volumes:
      - ./:/var/www/hrms:cached
      - be_vendor:/var/www/hrms/vendor
    working_dir: /var/www/hrms
    environment:
      - COMPOSER_MEMORY_LIMIT=-1    # Unlimited memory usage to allow `composer` require and update to run successfully

  db:
    image: mysql/mysql-server:8.0.28
    restart: always
    command:
      - --authentication-policy=mysql_native_password
      - --max_connections=302
    ports:
      - "4307:3306"
    platform: "linux/amd64"
    volumes:
      - data:/var/lib/mysql
      - "./docker/mysql_testing/init:/docker-entrypoint-initdb.d/"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hrms
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  node:
    image: node:16.4.0
    volumes:
      - ./:/var/www/hrms:cached
      - be_vendor:/var/www/hrms/vendor
      - be_node_modules:/var/www/hrms/node_modules
    working_dir: /var/www/hrms

volumes:
  data: ~
  be_vendor:
  be_node_modules:
